// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLOCehtIff08RAOxRhx45tDFrshLG1C0',
    appId: '1:716805581588:web:e77a9403016a4314dcf001',
    messagingSenderId: '716805581588',
    projectId: 'meals-final-project',
    authDomain: 'meals-final-project.firebaseapp.com',
    storageBucket: 'meals-final-project.firebasestorage.app',
    measurementId: 'G-8CXLH32JDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihytwLd4t6oGyCye7NdKYhgVq9MlUwKY',
    appId: '1:716805581588:android:42c2d3af02e0fb2bdcf001',
    messagingSenderId: '716805581588',
    projectId: 'meals-final-project',
    storageBucket: 'meals-final-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNfO8CEJ4mihirss2fGbsczfFqHLXmek',
    appId: '1:716805581588:ios:3c92c9da151b43f9dcf001',
    messagingSenderId: '716805581588',
    projectId: 'meals-final-project',
    storageBucket: 'meals-final-project.firebasestorage.app',
    iosBundleId: 'com.example.mealsFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNfO8CEJ4mihirss2fGbsczfFqHLXmek',
    appId: '1:716805581588:ios:3c92c9da151b43f9dcf001',
    messagingSenderId: '716805581588',
    projectId: 'meals-final-project',
    storageBucket: 'meals-final-project.firebasestorage.app',
    iosBundleId: 'com.example.mealsFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnLOCehtIff08RAOxRhx45tDFrshLG1C0',
    appId: '1:716805581588:web:1c486c29c435c9addcf001',
    messagingSenderId: '716805581588',
    projectId: 'meals-final-project',
    authDomain: 'meals-final-project.firebaseapp.com',
    storageBucket: 'meals-final-project.firebasestorage.app',
    measurementId: 'G-K3LN9RR8L1',
  );
}
